project:
  type: website
  output-dir: docs

website:
  title: "Andrew Burda"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Homework

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



